print("{:&^50}".format(" Multiplication tables "))

SomeNumber = int(input("Enter a number: "))
print("{:^50}".format("-" * 20))
print("{:^50}".format(" Multiplication tables "))
print("{:>20} X 1 = {}".format(SomeNumber, SomeNumber * 1))
print("{:>20} X 2 = {}".format(SomeNumber, SomeNumber * 2))
print("{:>20} X 3 = {}".format(SomeNumber, SomeNumber * 3))
print("{:>20} X 4 = {}".format(SomeNumber, SomeNumber * 4))
print("{:>20} X 5 = {}".format(SomeNumber, SomeNumber * 5))
print("{:>20} X 6 = {}".format(SomeNumber, SomeNumber * 6))
print("{:>20} X 7 = {}".format(SomeNumber, SomeNumber * 7))
print("{:>20} X 8 = {}".format(SomeNumber, SomeNumber * 8))
print("{:>20} X 9 = {}".format(SomeNumber, SomeNumber * 9))
print("{:>20} X 10 = {}".format(SomeNumber, SomeNumber * 10))
print("{:^50}".format("-" * 20))